### ISSUE TITLE
WithVariantFallback and WithVariantFallbackFunc are called when feature isn't found

### ISSUE THREAD

**Issue by jameshartig** [Unleash/unleash-client-go#160]
### Describe the bug

[WithVariantFallback](https://github.com/Unleash/unleash-client-go/blob/v4.0.1/config.go#L219) and [WithVariantFallbackFunc](https://github.com/Unleash/unleash-client-go/blob/v4.0.1/config.go#L227) both say they are called when no variant is found but they're actually called when a *feature* isn't found. There's no way to provide a fallback when variants aren't found.

### Steps to reproduce the bug

1. Call `GetVariant` on a non-existent feature with `WithVariantFallback`.
2. Observe fallback being used when the feature doesn't exist

### Expected behavior

I expected the options to match their descriptions and only be called when the variant isn't found. 

### Subscription type

Pro

### Hosting type

Hosted by Unleash

### SDK information (language and version)

Version 4.0.1

**Comment by thomasheartman** [comment]
I've done some digging, some comparing with other SDKs, and you're completely right 🙌🏼  The issue here is with the implementation. The fallback should be used when there is no flag, when the flag doesn't have any variants, and if the flag has variants, but is disabled.

If you feel like you wanna tackle this too, then we'd be very happy to review the PR when it comes through. If not, we'll pencil it in and probably get to fixing this early next week (depending on other incoming tasks).

**Comment by jameshartig** [comment]
> The fallback should be used when there is no flag, when the flag doesn't have any variants, and if the flag has variants, but is disabled.

I do believe this would resolve our issue. Thanks!

> If you feel like you wanna tackle this too, then we'd be very happy to review the PR when it comes through.

I didn't have any time today and my Monday is already booked. I'll post next week if Tuesday is better.

**Comment by thomasheartman** [comment]
> I didn't have any time today and my Monday is already booked. I'll post next week if Tuesday is better.

No worries! This was at the top of our pile today, so I got a PR up #171 that I believe should fix this 😄
