### ISSUE TITLE
Library flexibility

### ISSUE THREAD

**Issue by avirogalsky** [Unleash/unleash-client-go#71]
Currently there is a strong binding to unleash Context in all the library.
The main problem is that unleash Context is a struct that is already predefined for all unleash users.
I propose to redefine the context as an interface{} type with some API that can support current library and predefined strategies.
This way the user of the library can make much more flexible and power full use of context and custom strategies.

I can help implement the change if my suggestion accepted.

**Comment by ivarconr** [comment]
Hi @avirogalsky, the general idea is that Unleash comes with a set of defined context fields. In addition the user may define their own, which can be attached as the properties map. These will also be available in the strategy implementation. 


I am not sure if I understand what you are trying to achive by changing the implementation in to an interface?

**Comment by avirogalsky** [comment]
Hi @ivarconr, 2 reasons:
1. If it would be replaced by interface then custom strategies implementation may be much more flexible,  like moving a function as part of context.
2. I want to create an addon library for custom strategies by just implementing some interface, but now the Strategy interface depends on Context struct. So the addon library must be dependent on unleash-client-go and will to be updated each time we will want to update unleash-client-go library.

**Comment by jrbarron** [comment]
@avirogalsky I can see how using an interface instead of a struct would give you more flexibility here, but I don't think we could make this change in the `v3` branch because it would break compatibility for existing custom strategies that use the struct. We have a branch called `wip/v4` where we have been putting some changes that would break API compatibility, but it has not been updated in some time. If you decide to create a PR, I would recommend targeting that branch.

I think we would like to release the v4 client in conjunction with the v4 server to avoid confusion, but I'm not sure what the current status is for the v4 server. Perhaps @ivarconr has some comments on that.

**Comment by avirogalsky** [comment]
Thanks @jrbarron, indeed breaking API in `v3` is a bad idea.
I will get back to it once the v4 will be more relevant.
