### ISSUE TITLE
Publicly expose the default Strategies for faster and more advanced Strategies.

### ISSUE THREAD

**Issue by devaljain1998** [Unleash/unleash-client-go#90]
Hi Unleash team,

I request to propose to you a change for the notion of **"open-source development".**
We have a use-case where we have to gradually rollout a feature to the users in some cities.
As the strategies linked in frontend are executed in an OR fashion, we want to execute them in an AND fashion.

Example:
```python
class CityStrategy:
    def is_enabled(params, context):
          return context.properties["cities"] in params["cities"]
```
and combining it with gradual rollout strategy:
```python
class GradualRolloutCityStrategy:
    def is_enabled(params, context):
          return CityStrategy().is_enabled(params, context) and GradualRolloutStartegy.is_enabled(params, context)
```

Ability to use pre-defined strategy will take flexibility and possibilities with unleash-go to the next level. What do you think?
Hoping to get this issue ingrained in the library.

NOTE: These are not actual code snippets. Added just for demonstration purposes.

**Comment by FredrikOseberg** [comment]
@devaljain1998 Thanks for bringing this to our attention. I'm closing this because it is a duplicate issue of #42. I've added the tag "good first issue" and outlined the steps for completing the task in issue #42. 

Hopefully someone can take a stab at this and send a pull request with the code, otherwise it will have to wait until I can spare the time to implement this.
